//ADD A SUBMIT EVENT LISTENER ON THE FORM
    //STOP THE PAGE FROM REFRESHING WEHN THE FOR IS SUBMITTED
    // ONLY IF THE USER HAS ENTERED AN ACTUALTASK (AKA input is not empty):

//GRAB THE USER'S TO DO ITEM FROM THE FORM INPUT
//DISPLAY TO DO ON THE PAGE WITHIN AN LI ELEMENT
    //INCLUDE A CHECKBOX ICON WITHIN THE LI
//ADD THE LI ELEMENT TO THE UL
//CLICKING ON A TASK ALLOWS YOU TO TOGGLE BETWEEN CHECKED/UNCHECKED (AKA DONE V/S NOT DONE)


//ADD A RESET BUTTON WHICH CLEARS ALL OF THE TO DO'S
//ADD A REMOVE TASK BUTTON TO EACH TASK
//ADD A CONGRATULATION ALERT WHEN ALL OF THE EXISTING TO DO'S ARE CHECKED OFF